import { Geist, DM_Sans } from "next/font/google";
import "./globals.css";
import EzyPickNavbar from "@/_components/shared/EzyPickNavbar";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${dmSans.variable} antialiased`}>
        <Toaster />
        <EzyPickNavbar />
        {children}
      </body>
    </html>
  );
}
