import { Geist, DM_Sans } from "next/font/google";
import "./globals.css";
import EzyPickNavbar from "@/_components/shared/EzyPickNavbar";
import { Toaster } from "react-hot-toast";
import ThemeProviderWrapper from "../_ClientSideComponents/ThemeProviderWrapper";
import { AuthProvider } from "@/Context/AuthContext";

const dmSans = DM_Sans({
  variable: "--font-dm-sans", // Custom variable for Tailwind
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // Ensure all weights are available
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` ${dmSans.variable} antialiased`}>
        <ThemeProviderWrapper>
          <AuthProvider>
            <Toaster />
            <EzyPickNavbar />
            {children}
          </AuthProvider>
        </ThemeProviderWrapper>
      </body>
    </html>
  );
}
